version: "3.8"

services:
  api:
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BIOENERGY_ORG_API_LOCAL_PORT}:8080
    stdin_open: true
    tty: true
  client:
    depends_on:
      - api
    build:
      context: ./client
      args:
        VITE_BIOENERGY_ORG_API_URI: ${VITE_BIOENERGY_ORG_API_URI}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BIOENERGY_ORG_CLIENT_LOCAL_PORT}:80
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
    stdin_open: true
    tty: true
