version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${BIOENERGY_ORG_DB_NAME}
      POSTGRES_USER: ${BIOENERGY_ORG_DB_USER}
      POSTGRES_PASSWORD: ${BIOENERGY_ORG_DB_PASSWORD}
    ports:
      - ${BIOENERGY_ORG_DB_LOCAL_PORT}:${BIOENERGY_ORG_DB_CONTAINER_PORT}
    volumes:
      - db:/var/lib/postges
  api:
    depends_on:
      - postgres
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BIOENERGY_ORG_API_LOCAL_PORT}:${BIOENERGY_ORG_API_CONTAINER_PORT}
    stdin_open: true
    tty: true
  client:
    depends_on:
      - api
    build: ./client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BIOENERGY_ORG_CLIENT_LOCAL_PORT}:80
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
    stdin_open: true
    tty: true
volumes:
  db:
