version: "3.8"

services:
  api:
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BIOENERGY_ORG_API_LOCAL_PORT}:8080
    stdin_open: true
    tty: true
  client:
    depends_on:
      - api
    build: ./client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
    stdin_open: true
    tty: true
