version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BIOENERGY_ORG_API_LOCAL_PORT}:8080
    stdin_open: true
    tty: true
    develop:
      watch: # https://docs.docker.com/compose/how-tos/file-watch/
        - action: sync
          path: ./api
          target: /api
          ignore:
            - node_modules/
            - package-lock.json
        - action: rebuild
          path: package.json
  api-cron-sidecar:
    build: ./api
    restart: unless-stopped
    command: ["sh", "scripts/start_cron.sh"]
    env_file:
    - .env
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - ${BIOENERGY_ORG_CLIENT_LOCAL_PORT}:3000
    environment:
      - BIOENERGY_ORG_CLIENT_LOCAL_PORT
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - package-lock.json
        - action: rebuild
          path: package.json
    restart: unless-stopped
    env_file:
      - .env
    stdin_open: true
    tty: true
